go1.24.11.darwin-amd64.tar.gz:
  size: 80140733
  object_id: 24ae158e-872e-48da-48bc-040486e97beb
  sha: sha256:c45566cf265e2083cd0324e88648a9c28d0edede7b5fd12f8dc6932155a344c5
go1.24.11.linux-amd64.tar.gz:
  size: 78702669
  object_id: 74cbfe50-031b-4d6e-630e-ae6e9c813cc8
  sha: sha256:bceca00afaac856bc48b4cc33db7cd9eb383c81811379faed3bdbc80edb0af65
go1.24.11.windows-amd64.zip:
  size: 87287538
  object_id: 2ff9edb9-54ae-4df6-79e5-3a5c87c64f52
  sha: sha256:39f6267b6bb2a1c0daa83f563b3bf0a1a3e49925ecf6da854f7ff7d5e78d6968
go1.25.5.darwin-amd64.tar.gz:
  size: 60495242
  object_id: d2a0537b-d5cf-46fa-7fdd-d73eb6dc9b56
  sha: sha256:b69d51bce599e5381a94ce15263ae644ec84667a5ce23d58dc2e63e2c12a9f56
go1.25.5.linux-amd64.tar.gz:
  size: 59768009
  object_id: 09e99f28-85d5-4208-70e2-afef27de6ed1
  sha: sha256:9e9b755d63b36acf30c12a9a3fc379243714c1c6d3dd72861da637f336ebb35b
go1.25.5.windows-amd64.zip:
  size: 67442664
  object_id: e3f5f5b9-8eae-4f7e-5206-78c060515413
  sha: sha256:ae756cce1cb80c819b4fe01b0353807178f532211b47f72d7fa77949de054ebb
