go1.25.7.darwin-amd64.tar.gz:
  size: 60496692
  object_id: 53689250-0bb0-49e2-525f-5690997b03a2
  sha: sha256:bf5050a2152f4053837b886e8d9640c829dbacbc3370f913351eb0904cb706f5
go1.25.7.linux-amd64.tar.gz:
  size: 59768749
  object_id: eac41e05-0ce0-4704-5846-5aef5aac4414
  sha: sha256:12e6d6a191091ae27dc31f6efc630e3a3b8ba409baf3573d955b196fdf086005
go1.25.7.windows-amd64.zip:
  size: 67448678
  object_id: 37894f6c-0c5e-4899-5122-4ced94d938fc
  sha: sha256:c75e5f4ff62d085cc0017be3ad19d5536f46825fa05db06ec468941f847e3228
