go1.24.11.darwin-amd64.tar.gz:
  size: 80140733
  object_id: 24ae158e-872e-48da-48bc-040486e97beb
  sha: sha256:c45566cf265e2083cd0324e88648a9c28d0edede7b5fd12f8dc6932155a344c5
go1.24.11.linux-amd64.tar.gz:
  size: 78702669
  object_id: 74cbfe50-031b-4d6e-630e-ae6e9c813cc8
  sha: sha256:bceca00afaac856bc48b4cc33db7cd9eb383c81811379faed3bdbc80edb0af65
go1.24.11.windows-amd64.zip:
  size: 87287538
  object_id: 2ff9edb9-54ae-4df6-79e5-3a5c87c64f52
  sha: sha256:39f6267b6bb2a1c0daa83f563b3bf0a1a3e49925ecf6da854f7ff7d5e78d6968
go1.25.4.darwin-amd64.tar.gz:
  size: 60491166
  object_id: 26955f01-cd0c-403a-6293-3183382dc43a
  sha: sha256:33ba03ff9973f5bd26d516eea35328832a9525ecc4d169b15937ffe2ce66a7d8
go1.25.4.linux-amd64.tar.gz:
  size: 59766394
  object_id: 1507afca-ad78-4bee-50e2-0ef650c91df0
  sha: sha256:9fa5ffeda4170de60f67f3aa0f824e426421ba724c21e133c1e35d6159ca1bec
go1.25.4.windows-amd64.zip:
  size: 67441487
  object_id: 808eafb9-a893-4412-7a25-21325b96ef68
  sha: sha256:6dad204d42719795f22067553b2b042c0e710b32c5a00f6c67892865167fdfd0
