go1.24.12.darwin-amd64.tar.gz:
  size: 80148067
  object_id: ecf85f82-24cf-4e49-728a-a54211adbef8
  sha: sha256:4b9cc6771b56645da35a83a5424ae507f3250829b0d227e75f57b73e72da1f76
go1.24.12.linux-amd64.tar.gz:
  size: 78711173
  object_id: dd71bd8c-8e24-49fe-6709-d6dc9ae7c24d
  sha: sha256:bddf8e653c82429aea7aec2520774e79925d4bb929fe20e67ecc00dd5af44c50
go1.24.12.windows-amd64.zip:
  size: 87294602
  object_id: c84d4e94-a658-49ce-4fec-79f166f4494f
  sha: sha256:20e4bb6417117150d486181b16eaea4f1a9e7d8a2407a77da65d2b4e28dca53d
go1.25.7.darwin-amd64.tar.gz:
  size: 60496692
  object_id: 53689250-0bb0-49e2-525f-5690997b03a2
  sha: sha256:bf5050a2152f4053837b886e8d9640c829dbacbc3370f913351eb0904cb706f5
go1.25.7.linux-amd64.tar.gz:
  size: 59768749
  object_id: eac41e05-0ce0-4704-5846-5aef5aac4414
  sha: sha256:12e6d6a191091ae27dc31f6efc630e3a3b8ba409baf3573d955b196fdf086005
go1.25.7.windows-amd64.zip:
  size: 67448678
  object_id: 37894f6c-0c5e-4899-5122-4ced94d938fc
  sha: sha256:c75e5f4ff62d085cc0017be3ad19d5536f46825fa05db06ec468941f847e3228
