go1.24.10.darwin-amd64.tar.gz:
  size: 80126357
  object_id: 9d47ef0e-f794-4975-544b-03514da4fcd3
  sha: sha256:fde05d84f7f64c8d01564f299ea1897fe94457d20d8d9054200ac1f8ae1c2bc3
go1.24.10.linux-amd64.tar.gz:
  size: 78693970
  object_id: 5d45fc37-9866-41ef-4000-dc98c77ce44f
  sha: sha256:dd52b974e3d9c5a7bbfb222c685806def6be5d6f7efd10f9caa9ca1fa2f47955
go1.24.10.windows-amd64.zip:
  size: 87285017
  object_id: 7d93ea72-898b-45a7-5203-b23c13a2c1c6
  sha: sha256:2444fb53637facb37c06faa85d64c38c6cd23d22407f205edb68c7ddb8fbe0d4
go1.25.4.darwin-amd64.tar.gz:
  size: 60491166
  object_id: 26955f01-cd0c-403a-6293-3183382dc43a
  sha: sha256:33ba03ff9973f5bd26d516eea35328832a9525ecc4d169b15937ffe2ce66a7d8
go1.25.4.linux-amd64.tar.gz:
  size: 59766394
  object_id: 1507afca-ad78-4bee-50e2-0ef650c91df0
  sha: sha256:9fa5ffeda4170de60f67f3aa0f824e426421ba724c21e133c1e35d6159ca1bec
go1.25.4.windows-amd64.zip:
  size: 67441487
  object_id: 808eafb9-a893-4412-7a25-21325b96ef68
  sha: sha256:6dad204d42719795f22067553b2b042c0e710b32c5a00f6c67892865167fdfd0
