go1.24.12.darwin-amd64.tar.gz:
  size: 80148067
  object_id: ecf85f82-24cf-4e49-728a-a54211adbef8
  sha: sha256:4b9cc6771b56645da35a83a5424ae507f3250829b0d227e75f57b73e72da1f76
go1.24.12.linux-amd64.tar.gz:
  size: 78711173
  object_id: dd71bd8c-8e24-49fe-6709-d6dc9ae7c24d
  sha: sha256:bddf8e653c82429aea7aec2520774e79925d4bb929fe20e67ecc00dd5af44c50
go1.24.12.windows-amd64.zip:
  size: 87294602
  object_id: c84d4e94-a658-49ce-4fec-79f166f4494f
  sha: sha256:20e4bb6417117150d486181b16eaea4f1a9e7d8a2407a77da65d2b4e28dca53d
go1.25.6.darwin-amd64.tar.gz:
  size: 60492806
  object_id: 71f89ddc-3629-4fee-6e20-88e3bd5a8e63
  sha: sha256:e2b5b237f5c262931b8e280ac4b8363f156e19bfad5270c099998932819670b7
go1.25.6.linux-amd64.tar.gz:
  size: 59768880
  object_id: 5f43ffa5-0381-40e4-75e2-88a071281bf9
  sha: sha256:f022b6aad78e362bcba9b0b94d09ad58c5a70c6ba3b7582905fababf5fe0181a
go1.25.6.windows-amd64.zip:
  size: 67446385
  object_id: 34b39712-58b3-4e65-4738-d1e36c2f5cf8
  sha: sha256:19b4733b727ba5c611b5656187f3ac367d278d64c3d4199a845e39c0fdac5335
