go1.24.10.darwin-amd64.tar.gz:
  size: 80126357
  object_id: 9d47ef0e-f794-4975-544b-03514da4fcd3
  sha: sha256:fde05d84f7f64c8d01564f299ea1897fe94457d20d8d9054200ac1f8ae1c2bc3
go1.24.10.linux-amd64.tar.gz:
  size: 78693970
  object_id: 5d45fc37-9866-41ef-4000-dc98c77ce44f
  sha: sha256:dd52b974e3d9c5a7bbfb222c685806def6be5d6f7efd10f9caa9ca1fa2f47955
go1.24.10.windows-amd64.zip:
  size: 87285017
  object_id: 7d93ea72-898b-45a7-5203-b23c13a2c1c6
  sha: sha256:2444fb53637facb37c06faa85d64c38c6cd23d22407f205edb68c7ddb8fbe0d4
go1.25.3.darwin-amd64.tar.gz:
  size: 60491973
  object_id: d223f8dd-2541-450e-74c6-eed5dd081042
  sha: sha256:1641050b422b80dfd6299f8aa7eb8798d1cd23eac7e79f445728926e881b7bcd
go1.25.3.linux-amd64.tar.gz:
  size: 59767979
  object_id: c921b707-4f07-4aa2-5856-1f38212037e8
  sha: sha256:0335f314b6e7bfe08c3d0cfaa7c19db961b7b99fb20be62b0a826c992ad14e0f
go1.25.3.windows-amd64.zip:
  size: 67439680
  object_id: 4779545d-34b9-4eac-5c48-9c2da69f8732
  sha: sha256:bc249a599c6fe9d0d4093c363856f6c6320dbbe05e5d5d8818b711fb4a14fc23
